---
title: "California's Unlevel Playing Field"
authors: "Emma Durler, Kylie Scharf, Nicole Yee, Curtis LeQuang"
format: 
  pdf:
    embed-resources: true
    code-tools: true
    toc: true
    number-sections: true
    code-fold: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r} 
#| label: setup
#| output: false
library(tidyverse)
library(writexl)
#loading in data
tuesdata <- tidytuesdayR::tt_load('2022-03-29')
sports_dat <- tuesdata$sports

```

```{r}
#subsetting and moving data
library(tidyverse)
sports_dat2 <- sports_dat |>
  filter(sports == "Baseball" | sports == "Softball") |>
  mutate(
    rev_men = ifelse(is.na(rev_men), 0, rev_men),
    rev_women = ifelse(is.na(rev_women), 0, rev_women),
    exp_men = ifelse(is.na(exp_men), 0, exp_men),
    exp_women = ifelse(is.na(exp_women), 0, exp_women),
  ) |>
  filter(state_cd == "CA") |>
  rename(Sport = sports) |>
  group_by(Sport, year) |>
  pivot_wider(id_cols = year:sector_name, names_from = Sport, values_from = exp_men:exp_women) |>
  mutate(diff = exp_men_Baseball - exp_women_Softball)
```

```{r}
#| fig-alt: "The figure shows an overall positive trend for both college softball and baseball between average expenses and time from 2015 to 2018 for colleges in California. In 2019, however, the figure displays a slight negative trend for the average expenses for both sports. There appears to be more variability in the average expenses for baseball than for softball in any particular year. The average expenses for baseball are consistantly signifigantly larger than the expenses for women, although the expenses for both sports tend to increase at a similiar rate over time."
#| fig-cap: "Above entails an analysis of the differences in average expenses from 2015 to 2019 for collegiate baseball and softball in California. The Department of Education collects data yearly on collegiate sports budgets in accordance to The Equity in Althletics Disclosure Act. The graph above consists of such data subsetted to contain soley softball and baseball teams from California in the years 2015 to 2019. The expense for a particular year averaged over all California softball teams is plotted as a blue triangle, wheras the expense averaged over all California baseball teams in a particular year is plotted as a red circle. The highlighted region represents adding or subtracting one standard error of the average from the plotted averages. There appears to be more variability in the average expenses for baseball than for softball in any particular year in California. The average expenses for baseball are consistantly signifigantly larger than the expenses for women, although the expenses for both sports tend to increase at a similiar rate over time."


plot <- sports_dat |>
  filter(sports == "Baseball" | sports == "Softball") |>
  rename(Sport = sports) |>
  group_by(Sport, year) |>
  filter(total_exp_menwomen != 0) |>
  summarise(mean_exp = mean(total_exp_menwomen), stan = sd(total_exp_menwomen)/sqrt(n())) |>
  ggplot(aes(y = mean_exp, x = year, color = Sport, shape=Sport, fill=Sport)) +
   geom_ribbon(aes(ymin = mean_exp - stan, ymax = mean_exp + stan), alpha=.5, color=NA) +
  geom_point(size=4) +
  geom_line() +
  labs(x = "Year", subtitle = "Average Yearly Expense", y = "", title = "Fig 1. California College Baseball And Softball Expenses Over Time", caption = "Data Source (Department of Education)") +
theme(plot.caption = element_text(hjust = 0)) + 
scale_y_continuous(labels = scales::dollar)

plot

```

```{r}
library(rstatix)
library(kableExtra)
table <- sports_dat |>
  filter(sports == "Baseball" | sports == "Softball") |>
  rename(Sport = sports) |>
  group_by(Sport, year) |>
  filter(total_exp_menwomen != 0) |>
  summarise(mean_exp = mean(total_exp_menwomen)) |>
  pivot_wider(id_cols = year, names_from = Sport, values_from = mean_exp) |>
  rename(Year=year, Expenses_Men=Baseball, Expenses_Women=Softball)

kable(table,
      caption="<center>Table 1: CA Collegiate Baseball and Softball Expenses<center>",
      col.names = c("Year", 
                    "Expenses Baseball ($)", 
                    "Expenses Softball ($)")) |>
  kable_classic() |>
  kable_styling(full_width = FALSE, position = "center") |>
  footnote(general="Source: Department of Education")

t.test(sports_dat2$exp_men_Baseball, sports_dat2$exp_women_Softball, paired=TRUE)
```

