
```{r} 
#| label: setup
#| output: false
library(tidyverse)
tuesdata <- tidytuesdayR::tt_load('2022-03-29')
sports_dat <- tuesdata$sports

```

```{r}
sports_dat <- sports_dat |>
  filter(sports == "Baseball" | sports == "Softball") |>
  mutate(
    rev_men = ifelse(is.na(rev_men), 0, rev_men),
    rev_women = ifelse(is.na(rev_women), 0, rev_women),
    exp_men = ifelse(is.na(exp_men), 0, exp_men),
    exp_women = ifelse(is.na(exp_women), 0, exp_women),
    total_exp_menwomen = ifelse(is.na(total_exp_menwomen),0,total_exp_menwomen)
  ) |>
  filter(state_cd == "CA")

sports_dat <- sports_dat |>
  rename(Sport = sports)
```

```{r}
#| fig-alt: "The figure shows an overall positive trend for both college softball and baseball between average expenses and time from 2015 to 2018 for colleges in California. In 2019, however, the figure displays a slight negative trend for the average expenses for both sports. There appears to be more variability in the average expenses for baseball than for softball in any particular year. The average expenses for baseball are consistantly signifigantly larger than the expenses for women, although the expenses for both sports tend to increase at a similiar rate over time."
#| fig-cap: "Above entails an analysis of the differences in average expenses from 2015 to 2019 for collegiate baseball and softball in California.  The expense for a particular year averaged over all California softball teams is plotted as a red triangle, wheras the expense averaged over all California baseball teams in a particular year is plotted as a blue circle. The grey highlighted region represents adding or subtracting one standard error of the average from the plotted averages. There appears to be more variability in the average expenses for baseball than for softball in any particular year in California. The average expenses for baseball are consistantly larger than the expenses for women, although the expenses for both sports tend to increase at a similiar rate over time."



plot <- sports_dat |>
  group_by(Sport, year) |>
  filter(total_exp_menwomen != 0) |>
  summarise(mean_exp = mean(total_exp_menwomen), stan = sd(total_exp_menwomen)/sqrt(n())) |>
  ggplot(aes(y = mean_exp, x = year, color = Sport, shape=Sport, fill=Sport)) +
   geom_ribbon(aes(ymin = mean_exp - stan, ymax = mean_exp + stan), alpha=.5, color="grey", fill = "lavender") +
  theme_bw() +
  theme_light() +
  geom_point(size=4) +
  geom_line() +
  labs(x = "Year", subtitle = "Average Yearly Expense", y = "", title = "Fig 1. A Disparity in California College Baseball and Softball Expenses", caption = "Data Source (Department of Education)") +
theme(plot.caption = element_text(hjust = 0)) + 
scale_y_continuous(labels = scales::dollar, limits=c(0,600000)) +
scale_color_manual(values=c('Blue','red'))

plot

```